doctrine:
    # tbd: multiple connections by privileges
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # register custom types
        # cf. https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#custom-mapping-types
        types:
            geschlecht:
                class: App\DBAL\Type\EnumGenderType
                commented: false
        ## or:
#        mapping_types:
#            geschlecht: string

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            soft_delete:
                class: App\DBAL\Query\Filter\IsSoftDeletedFilter
                enabled: true